import sys

domain = sys.path[0].replace("scripts", "domain")
sys.path.append(domain)

import desenha_grafo as dg

imagem_grafo = dg.DesenhaGrafo()

imagem_grafo.adiciona_vertice("Vila Natal")
imagem_grafo.adiciona_vertice("Capão Redondo")
imagem_grafo.adiciona_vertice("Santo Amaro")
imagem_grafo.adiciona_vertice("Pinheiros")
imagem_grafo.adiciona_vertice("Vila Sônia")
imagem_grafo.adiciona_vertice("Osasco")
imagem_grafo.adiciona_vertice("Itapevi")
imagem_grafo.adiciona_vertice("Paulista")
imagem_grafo.adiciona_vertice("Vila Madalena")
imagem_grafo.adiciona_vertice("Paraíso")
imagem_grafo.adiciona_vertice("República")
imagem_grafo.adiciona_vertice("Barra Funda")
imagem_grafo.adiciona_vertice("Sé")
imagem_grafo.adiciona_vertice("Luz")
imagem_grafo.adiciona_vertice("Tucuruvi")
imagem_grafo.adiciona_vertice("Jundiaí")
imagem_grafo.adiciona_vertice("Jabaquara")
imagem_grafo.adiciona_vertice("Tamanduateí")
imagem_grafo.adiciona_vertice("Brás")
imagem_grafo.adiciona_vertice("Rio Grande da Serra")
imagem_grafo.adiciona_vertice("Jardim Colonial")
imagem_grafo.adiciona_vertice("Artur Alvim")
imagem_grafo.adiciona_vertice("Estudantes")
imagem_grafo.adiciona_vertice("Aracaré")
imagem_grafo.adiciona_vertice("Engº Goulart")
imagem_grafo.adiciona_vertice("Guarulhos")

imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Vila Natal"), imagem_grafo.busca_vertice("Santo Amaro"), 6)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Capão Redondo"), imagem_grafo.busca_vertice("Santo Amaro"), 4)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Santo Amaro"), imagem_grafo.busca_vertice("Pinheiros"), 8)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Santo Amaro"), imagem_grafo.busca_vertice("Paraíso"), 14)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Pinheiros"), imagem_grafo.busca_vertice("Vila Sônia"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Pinheiros"), imagem_grafo.busca_vertice("Osasco"), 5)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Pinheiros"), imagem_grafo.busca_vertice("Paulista"), 4)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Paulista"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Sé"), 4)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Jabaquara"), 8)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Tamanduateí"), 6)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Osasco"), imagem_grafo.busca_vertice("Itapevi"), 13)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Osasco"), imagem_grafo.busca_vertice("Barra Funda"), 5)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paulista"), imagem_grafo.busca_vertice("Vila Madalena"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paulista"), imagem_grafo.busca_vertice("República"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Barra Funda"), imagem_grafo.busca_vertice("Jundiaí"), 16)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Barra Funda"), imagem_grafo.busca_vertice("República"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("República"), imagem_grafo.busca_vertice("Sé"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("República"), imagem_grafo.busca_vertice("Luz"), 1)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Sé"), imagem_grafo.busca_vertice("Luz"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Sé"), imagem_grafo.busca_vertice("Brás"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Luz"), imagem_grafo.busca_vertice("Brás"), 1)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Luz"), imagem_grafo.busca_vertice("Tucuruvi"), 8)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Tamanduateí"), imagem_grafo.busca_vertice("Rio Grande da Serra"), 9)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Tamanduateí"), imagem_grafo.busca_vertice("Jardim Colonial"), 11)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Tamanduateí"), imagem_grafo.busca_vertice("Brás"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Brás"), imagem_grafo.busca_vertice("Artur Alvim"), 9)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Brás"), imagem_grafo.busca_vertice("Estudantes"), 14)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Brás"), imagem_grafo.busca_vertice("Engº Goulart"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Engº Goulart"), imagem_grafo.busca_vertice("Aracaré"), 10)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Engº Goulart"), imagem_grafo.busca_vertice("Guarulhos"), 2)

imagem_grafo.mostra_grafo()