import sys

domain = sys.path[0].replace("scripts", "domain")
sys.path.append(domain)

import desenha_grafo as dg

imagem_grafo = dg.DesenhaGrafo()

imagem_grafo.adiciona_vertice("Vila Natal", 5, 1)
imagem_grafo.adiciona_vertice("Capão Redondo", 2, 5)
imagem_grafo.adiciona_vertice("Santo Amaro", 5, 5)
imagem_grafo.adiciona_vertice("Pinheiros", 5, 15)
imagem_grafo.adiciona_vertice("Vila Sônia", 2, 15)
imagem_grafo.adiciona_vertice("Osasco", 5, 20)
imagem_grafo.adiciona_vertice("Itapevi", 1, 20)
imagem_grafo.adiciona_vertice("Paulista", 8, 15)
imagem_grafo.adiciona_vertice("Vila Madalena", 7, 17)
imagem_grafo.adiciona_vertice("Paraíso", 12, 10)
imagem_grafo.adiciona_vertice("República", 10, 18)
imagem_grafo.adiciona_vertice("Barra Funda", 10, 21)
imagem_grafo.adiciona_vertice("Sé", 12, 18)
imagem_grafo.adiciona_vertice("Luz", 12, 21)
imagem_grafo.adiciona_vertice("Tucuruvi", 12, 25)
imagem_grafo.adiciona_vertice("Jundiaí", 5, 30)
imagem_grafo.adiciona_vertice("Jabaquara", 12, 4)
imagem_grafo.adiciona_vertice("Tamanduateí", 18, 10)
imagem_grafo.adiciona_vertice("Brás", 14, 18)
imagem_grafo.adiciona_vertice("Rio Grande da Serra", 22, 5)
imagem_grafo.adiciona_vertice("Jardim Colonial", 23, 10)
imagem_grafo.adiciona_vertice("Artur Alvim", 20, 18)
imagem_grafo.adiciona_vertice("Estudantes", 25, 21)
imagem_grafo.adiciona_vertice("Aracaré", 22, 21)
imagem_grafo.adiciona_vertice("Engº Goulart", 18, 21)
imagem_grafo.adiciona_vertice("Guarulhos", 21, 30)

imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Vila Natal"), imagem_grafo.busca_vertice("Santo Amaro"), 6)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Capão Redondo"), imagem_grafo.busca_vertice("Santo Amaro"), 4)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Santo Amaro"), imagem_grafo.busca_vertice("Pinheiros"), 8)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Santo Amaro"), imagem_grafo.busca_vertice("Paraíso"), 14)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Pinheiros"), imagem_grafo.busca_vertice("Vila Sônia"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Pinheiros"), imagem_grafo.busca_vertice("Osasco"), 5)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Pinheiros"), imagem_grafo.busca_vertice("Paulista"), 4)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Paulista"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Sé"), 4)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Jabaquara"), 8)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paraíso"), imagem_grafo.busca_vertice("Tamanduateí"), 6)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Osasco"), imagem_grafo.busca_vertice("Itapevi"), 13)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Osasco"), imagem_grafo.busca_vertice("Barra Funda"), 5)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paulista"), imagem_grafo.busca_vertice("Vila Madalena"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Paulista"), imagem_grafo.busca_vertice("República"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Barra Funda"), imagem_grafo.busca_vertice("Jundiaí"), 16)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Barra Funda"), imagem_grafo.busca_vertice("República"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("República"), imagem_grafo.busca_vertice("Sé"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("República"), imagem_grafo.busca_vertice("Luz"), 1)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Sé"), imagem_grafo.busca_vertice("Luz"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Sé"), imagem_grafo.busca_vertice("Brás"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Luz"), imagem_grafo.busca_vertice("Brás"), 1)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Luz"), imagem_grafo.busca_vertice("Tucuruvi"), 8)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Tamanduateí"), imagem_grafo.busca_vertice("Rio Grande da Serra"), 9)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Tamanduateí"), imagem_grafo.busca_vertice("Jardim Colonial"), 11)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Tamanduateí"), imagem_grafo.busca_vertice("Brás"), 3)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Brás"), imagem_grafo.busca_vertice("Artur Alvim"), 9)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Brás"), imagem_grafo.busca_vertice("Estudantes"), 14)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Brás"), imagem_grafo.busca_vertice("Engº Goulart"), 2)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Engº Goulart"), imagem_grafo.busca_vertice("Aracaré"), 10)
imagem_grafo.adiciona_aresta(imagem_grafo.busca_vertice("Engº Goulart"), imagem_grafo.busca_vertice("Guarulhos"), 2)

imagem_grafo.mostra_grafo()